export const ROUTES = {
  home: '/',
  login: '/login',
  verifyOtp: '/verify-otp',
  activate: '/activate',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  rfqs: '/rfqs',
  rfqDetail: '/rfqs/:id',
  rfqResponse: '/rfqs/:id/response',
  purchaseOrders: '/purchase-orders',
  purchaseOrderNew: '/purchase-orders/new',
  purchaseOrderDetail: '/purchase-orders/:id',
  purchaseOrderComms: '/purchase-orders/:id/comms',
  purchaseOrderChangeRequest: '/purchase-orders/:id/change-request',
  bulkOrders: '/bulk-orders',
  bulkOrderDetail: '/bulk-orders/:id',
  bulkOrderChange: '/bulk-orders/:id/change',
  bulkOrderReviewChange: '/bulk-orders/:id/review-change',

  invoiceDetail: '/invoices/:id',
  users: '/users',
  userDetail: '/users/:id',
  settings: '/settings',
  me: '/me',
  companyProfile: '/company',
  materialDetail: '/materials/:id',
  guestInvitation: '/invitation/:token',
} as const;
