-- AlterEnum: Add new PoStatus values
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'DECLINED';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'SCHEDULED_FOR_DELIVERY';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_DELIVERED';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'LATE_FOR_DELIVERY';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'CANCELLED_BY_VENDOR';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'INVOICED';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'DISPUTE';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'NOT_DELIVERED';
ALTER TYPE "PoStatus" ADD VALUE IF NOT EXISTS 'CHANGE_PENDING';

-- AlterEnum: Add new PoType values
ALTER TYPE "PoType" ADD VALUE IF NOT EXISTS 'BULK';
ALTER TYPE "PoType" ADD VALUE IF NOT EXISTS 'DRAWDOWN';
ALTER TYPE "PoType" ADD VALUE IF NOT EXISTS 'SPLIT';

-- CreateEnum: ApprovalStatus
DO $$ BEGIN
  CREATE TYPE "ApprovalStatus" AS ENUM ('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateEnum: PoSourceOfCreation
DO $$ BEGIN
  CREATE TYPE "PoSourceOfCreation" AS ENUM ('RFQ', 'BULK_DRAWDOWN', 'MATERIAL_REQUEST', 'MANUAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateEnum: PaymentTerm
DO $$ BEGIN
  CREATE TYPE "PaymentTerm" AS ENUM ('NET15', 'NET30', 'NET45', 'NET60');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateEnum: PoPriority
DO $$ BEGIN
  CREATE TYPE "PoPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateEnum: PoChangeType
DO $$ BEGIN
  CREATE TYPE "PoChangeType" AS ENUM ('COMMERCIAL', 'INTERNAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
