#!/usr/bin/env bash
# remote-deploy.sh — runs on the EC2 backend host via aws ssm send-command.
#
# Reads /forethread/${env}/* from SSM Parameter Store + /forethread-backend/${env}/*
# from Secrets Manager, assembles /etc/forethread/backend.env, then
# `docker compose pull && docker compose up -d backend`.
#
# Expects FORETHREAD_ENV to be exported by the caller (the deploy workflow does this).

set -euo pipefail

ENV="${FORETHREAD_ENV:-staging}"
REGION="$(curl -sf http://169.254.169.254/latest/meta-data/placement/region || echo eu-north-1)"
SSM_PREFIX="/forethread/${ENV}"
SECRETS_PREFIX="/forethread-backend/${ENV}"

log() { echo "[$(date -u +%H:%M:%S)] $*"; }

log "=== Deploy starting for env=${ENV} region=${REGION} ==="

############################################
# 1. Read SSM parameters
############################################

ssm_get() {
  aws ssm get-parameter --region "$REGION" --name "$1" --with-decryption --query 'Parameter.Value' --output text
}

sm_get() {
  aws secretsmanager get-secret-value --region "$REGION" --secret-id "$1" --query 'SecretString' --output text
}

log "Reading SSM contract..."
RDS_ENDPOINT=$(ssm_get "${SSM_PREFIX}/rds/endpoint")    # host:port
RDS_PORT=$(ssm_get "${SSM_PREFIX}/rds/port")
RDS_DB=$(ssm_get "${SSM_PREFIX}/rds/db-name")
RDS_SECRET_ARN=$(ssm_get "${SSM_PREFIX}/rds/master-secret-arn")
REDIS_URL=$(ssm_get "${SSM_PREFIX}/redis/url")
S3_BUCKET=$(ssm_get "${SSM_PREFIX}/s3/uploads/bucket")
S3_REGION=$(ssm_get "${SSM_PREFIX}/s3/uploads/region")
ECR_URI=$(ssm_get "${SSM_PREFIX}/ecr/backend/repository-url")
LOG_GROUP=$(ssm_get "${SSM_PREFIX}/observability/log-group-name")

############################################
# 2. Fetch RDS master credentials and form DATABASE_URL
############################################

log "Fetching RDS master credentials..."
RDS_CREDS_JSON=$(sm_get "$RDS_SECRET_ARN")
RDS_USER=$(echo "$RDS_CREDS_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['username'])")
RDS_PASS=$(echo "$RDS_CREDS_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['password'])")

# URL-encode the password to survive special characters
RDS_PASS_ENC=$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=''))" "$RDS_PASS")

# RDS endpoint is "host:port"; the master secret usually carries port too but
# we trust the SSM parameter for the canonical port value.
RDS_HOST="${RDS_ENDPOINT%:*}"
DATABASE_URL="postgresql://${RDS_USER}:${RDS_PASS_ENC}@${RDS_HOST}:${RDS_PORT}/${RDS_DB}?schema=public"

############################################
# 3. Fetch app secrets
############################################

log "Fetching app secrets..."
JWT_ACCESS=$(sm_get "${SECRETS_PREFIX}/jwt-access-secret")
JWT_REFRESH=$(sm_get "${SECRETS_PREFIX}/jwt-refresh-secret")
RESEND_KEY=$(sm_get "${SECRETS_PREFIX}/resend-api-key")
GEMINI_KEY=$(sm_get "${SECRETS_PREFIX}/gemini-api-key")
PLACES_KEY=$(sm_get "${SECRETS_PREFIX}/google-places-api-key")
SENTRY_DSN=$(sm_get "${SECRETS_PREFIX}/sentry-dsn" 2>/dev/null || echo "")

############################################
# 4. Assemble /etc/forethread/backend.env
############################################
#
# Values not yet in the SSM contract (APP_URL, WEB_APP_URL, CORS_ORIGINS,
# RESEND_FROM) are hard-coded sensible defaults. Once DNS is pointed at the
# Elastic IP and Resend's sender domain is verified, replace these via SSM
# Parameter Store and re-deploy.

log "Writing /etc/forethread/backend.env"
install -d -m 0755 /etc/forethread

# Build the env file atomically: write to .tmp, then mv.
cat > /etc/forethread/backend.env.tmp <<EOF
# Generated by remote-deploy.sh - do not edit by hand
NODE_ENV=production
PORT=3000
LOG_LEVEL=info
FORETHREAD_ENV=${ENV}
AWS_REGION=${REGION}

# Database
DATABASE_URL=${DATABASE_URL}
DATABASE_CONNECTION_LIMIT=10
DATABASE_POOL_TIMEOUT=10

# Redis
REDIS_URL=${REDIS_URL}

# JWT
JWT_ACCESS_SECRET=${JWT_ACCESS}
JWT_REFRESH_SECRET=${JWT_REFRESH}
JWT_ACCESS_EXPIRES_IN=4h
JWT_REFRESH_EXPIRES_IN=7d

# Email - Resend
RESEND_API_KEY=${RESEND_KEY}
RESEND_FROM=notifications@updates.forethread.com

# Email - SMTP (unused with Resend, but some code paths may read it)
SMTP_HOST=
SMTP_PORT=0
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=
SMTP_FROM=notifications@updates.forethread.com

# S3 uploads (IAM role on the instance provides credentials; access keys left unset)
S3_BUCKET=${S3_BUCKET}
S3_REGION=${S3_REGION}
S3_FORCE_PATH_STYLE=false

# Observability
SENTRY_DSN=${SENTRY_DSN}

# CORS - the deployed Vercel frontend origin. The web api-client sends cookies
# (withCredentials: true), so this MUST be the exact origin — a browser rejects
# "*" with credentialed requests, and NestJS treats ["*"] as a literal (matches
# nothing). Comma-separate to allow more origins (e.g. preview deploys).
CORS_ORIGINS=https://forethread-main.vercel.app

# Rate limiting
THROTTLE_TTL_MS=60000
THROTTLE_LIMIT=100

# Google APIs
GOOGLE_PLACES_API_KEY=${PLACES_KEY}
GEMINI_API_KEY=${GEMINI_KEY}
GEMINI_MODEL=gemini-2.5-flash
GEMINI_TIMEOUT_MS=60000
GEMINI_THINKING_BUDGET=0

# App URLs. APP_URL is the backend's own public base (behind Caddy at the
# api-main domain); WEB_APP_URL is the deployed frontend, used to build links
# in outbound emails and the vendor tokenized-portal flow.
APP_URL=https://api-main.forethread.com
WEB_APP_URL=https://forethread-main.vercel.app
EOF

chmod 0640 /etc/forethread/backend.env.tmp
mv -f /etc/forethread/backend.env.tmp /etc/forethread/backend.env
log "/etc/forethread/backend.env written ($(wc -l < /etc/forethread/backend.env) lines)"

############################################
# 5. ECR login (instance role - already permissioned for forethread-* repos)
############################################

log "Logging in to ECR..."
aws ecr get-login-password --region "$REGION" \
  | docker login --username AWS --password-stdin "${ECR_URI%/*}"

############################################
# 6. Pull image, apply migrations, (re)start the backend service
############################################

cd /opt/forethread-backend
log "docker compose pull backend..."
docker compose pull backend

# Apply pending Prisma migrations before the app starts. `migrate deploy` only
# applies migrations that have not run yet (no schema-from-diff, no data loss)
# and is a no-op when the DB is already current, so it is safe to run on every
# deploy. It runs as a one-shot container via the entrypoint's `migrate` command
# (waits for the DB, then `prisma migrate deploy`); -T disables TTY allocation
# for the non-interactive SSM context. Without this the backend boots against an
# unmigrated database and crash-loops (e.g. "table public.permissions does not
# exist"). `set -e` aborts the deploy if a migration fails.
log "Applying database migrations (prisma migrate deploy)..."
docker compose run --rm -T backend migrate

log "docker compose up -d backend..."
docker compose up -d backend

log "Waiting for backend container to be healthy..."
for i in $(seq 1 24); do
  STATE=$(docker inspect --format='{{.State.Status}}' forethread-backend-backend-1 2>/dev/null || echo "missing")
  HEALTH=$(docker inspect --format='{{if .State.Health}}{{.State.Health.Status}}{{else}}n/a{{end}}' forethread-backend-backend-1 2>/dev/null || echo "n/a")
  echo "  [$i] state=${STATE} health=${HEALTH}"
  if [ "$STATE" = "running" ] && { [ "$HEALTH" = "healthy" ] || [ "$HEALTH" = "n/a" ]; }; then
    log "Backend up."
    docker compose ps
    exit 0
  fi
  if [ "$STATE" = "exited" ]; then
    log "::error::Backend container exited. Last 50 lines:"
    docker logs --tail 50 forethread-backend-backend-1 || true
    exit 1
  fi
  sleep 5
done

log "::warning::Backend container did not become healthy within 2 minutes. Last log lines:"
docker logs --tail 50 forethread-backend-backend-1 || true
docker compose ps
exit 1
